# Generated by Django 4.0.4 on 2022-05-12 10:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0005_propertieskey_propertiesvalue_product_properties'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='propertiesvalue',
            options={'ordering': ['value']},
        ),
        migrations.AlterField(
            model_name='propertiesvalue',
            name='value',
            field=models.JSONField(),
        ),
    ]
